### ISSUE TITLE
Create a 'Splash' Page

### ISSUE THREAD

**Issue by ghost** [aish12/parksrus#12]
As a requirement for Phase 1, we must have a beautiful Splash page to capture our users' attention and make our website appealing.

The Splash Page must satisfy the following requirements:
- [x] Be Beautiful
- [x] Allow Page Navigation
- [x] Carousel

This should take 1 hour.

**Comment by aish12** [comment]
Should we consider having each picture displayed in a smaller size so that we don't have to scroll at the beginning?

**Comment by ghost** [comment]
@aish12 I believe the idea of not requiring our users to scroll to see the entire splash page is definitely on point! 

However, I think the issue is that our implementation must be able to maintain the ability to adapt to different screen resolutions. In an ideal implementation, we would have multiple high-quality versions of the same hero image at multiple screen resolutions, as opposed to stretching a single image as a one-size-fits-all approach. That said, for Milestone 1, I think we can at least try to reduce the size of the image via the CSS as opposed to needing to manually edit the files directly.

**Comment by danielczheng** [comment]
@trentonbeckendorff I think the problem with images with different resolutions could be solved with cropping and resizing images instead of stretching. Consider these ideas: 

[https://stackoverflow.com/questions/493296/css-display-an-image-resized-and-cropped](https://www.w3schools.com/cssref/pr_pos_clip.asp)
[https://stackoverflow.com/questions/493296/css-display-an-image-resized-and-cropped](https://stackoverflow.com/questions/493296/css-display-an-image-resized-and-cropped)

**Comment by aish12** [comment]
This item took 2 hours to complete.
