### ISSUE TITLE
More filters

### ISSUE THREAD

**Issue by JeffJiang42** [aish12/parksrus#63]
For filtering and sorting, we would like to have more options (e.g. filter out parks with a rating below 2). In addition, it is unclear that the displayed switch is to toggle ascending/descending. It would be good to clarify the functionality of this switch.

**Comment by ghost** [comment]
Hello, Jeff!

I've added additional filtering options for the Parks model grid using a similar binning approach as to what was previously available for the implementation of filtering by review_data for the theme parks. Now, for example, you can filter cities that have 15+ parks or more. Unfortunately, due to the significant refactoring that would be required, we have opted not to pursue implementation of the addition of the number of tags each snapshot is associated with, thereby limiting the filtering options we are able to provide for our snapshots. We are currently looking into how to the possibility of allowing users to filter snapshots by state. We estimated the changes implemented thus far would require 3 hours, the actual time required was 2 hours.
